### ISSUE TITLE
Add css

### ISSUE THREAD

**Issue by abdulsamad234** [abdulsamad234/testt#11]
Add a css directory and create a blank stylesheet.css file and link to it in the index.html file.

**Comment by aakarshachug19** [comment]
To add external css sheet
1. Create a new file stylesheet.css where you will write your css code.
2. Now in your html file i.e- index.html write the link of that sheet
<head>
<link rel="stylesheet" type="text/css" href="stylesheet.css">
</head>
this will link your external css file with your html page

**Comment by dalcinj** [comment]
I can do it.

**Comment by abdulsamad234** [comment]
@Aakarsha19chugh  Thank you
